# Generated by Django 4.2.4 on 2024-03-06 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_cuenta_groups_cuenta_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='last_login',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2024, 3, 6, 15, 16, 35, 750213, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
