# Generated by Django 4.2.4 on 2024-05-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_alter_cuenta_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
    ]
