# Generated by Django 4.2.4 on 2024-03-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.BigAutoField(primary_key=True, serialize=False)),
                ('proveedor_name', models.CharField(max_length=50)),
                ('logo', models.BinaryField()),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Post',
            },
        ),
    ]
