# Generated by Django 4.2.4 on 2024-03-06 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 3, 6, 14, 25, 37, 809569, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
