# Generated by Django 4.2.4 on 2024-03-07 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proveedor', '0003_post_actualizado_post_creado_alter_post_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('contrasenia', models.CharField(max_length=254)),
                ('capacidad_tanque', models.CharField(max_length=5)),
                ('correo', models.EmailField(max_length=254)),
                ('calle', models.CharField(max_length=254)),
                ('numero_interior', models.CharField(max_length=10)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('ciudad', models.CharField(max_length=15)),
                ('colonia', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('apellido_cliente', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('litros', models.DecimalField(decimal_places=2, max_digits=3)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calle', models.CharField(max_length=254)),
                ('numero_interior', models.CharField(max_length=10)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('ciudad', models.CharField(max_length=254)),
                ('colonia', models.CharField(max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proveedor.post')),
            ],
            options={
                'db_table': 'Pedido',
            },
        ),
    ]
