# Generated by Django 4.2.4 on 2023-10-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('contrasenia', models.CharField(max_length=254)),
                ('capacidad_tanque', models.CharField(max_length=5)),
                ('correo', models.EmailField(max_length=254)),
                ('calle', models.CharField(max_length=254)),
                ('numero_interior', models.CharField(max_length=10)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('ciudad', models.CharField(max_length=15)),
                ('colonia', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
    ]
