# Generated by Django 4.2.4 on 2024-05-08 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pedido',
            table='pedido',
        ),
    ]
